agent:
  name: "InsuranceRAG"
  version: "1.0.0"
  created_by: "objectgyan"
  created_at: "2025-01-20 23:18:40"

vector_store:
  backend: "chroma"
  persist_directory: "data/chroma"
  embedding_model: "all-MiniLM-L6-v2"
  distance_metric: "cosine"
  n_results: 3

llm:
  provider: "local"
  model: "facebook/opt-350m"
  temperature: 0.3
  max_tokens: 500
  use_cache: true
  cache_dir: "cache/models"
  device: "cuda"
  cuda_version: "12.2"
  driver_version: "538.78"
  system_prompt: "You are an insurance policy assistant. Provide accurate, clear answers based only on the provided policy information."

document_processor:
  chunk_size: 1000
  chunk_overlap: 200
  max_chunks: 10